changelog:
  exclude:
    labels:
      - exclude-changelog
  categories:
    - title: Features, fixes, enhancements 🎉
      labels:
        - '*'
      exclude:
        labels:
          - maintenance
    - title: Maintenance 🛠
      labels:
        - maintenance
