targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - swaggers/**
    builders:
      slang_build_runner:
        options:
          base_locale: de
          fallback_strategy: base_locale
          input_file_pattern: .json
          input_directory: lib/i18n
          output_file_name: translations.g.dart
          output_directory: lib/i18n
      chopper_generator:
        options:
          header: "// Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "swaggers/"
          output_folder: "lib/swagger_generated_code/"
          multipart_file_type: "MultipartFile"
