description: Restores and saves the cocoa pods cache.
steps:
  - restore_cache:
      name: Restore CocoaPods Cache
      keys:
        - 1-cocoapods-{{ arch }}-{{ checksum "ios/Podfile.lock" }}
  - run:
      name: Install CocoaPods
      command: |
        pod update
        pod install
      working_directory: ios
  - save_cache:
      name: Save CocoaPods Cache
      key: 1-cocoapods-{{ arch }}-{{ checksum "ios/Podfile.lock" }}
      paths:
        - ~/Library/Caches/CocoaPods/
