steps:
  - restore_cache:
      keys:
        - brew-dart-4
  - run:
      name: Install Dart
      command: |
        brew tap dart-lang/dart
        brew install dart@3.3.1
        brew link dart@3.3.1
  - save_cache:
      key: brew-dart-4
      paths:
        - /usr/local/Cellar/dart/
        - /usr/local/Homebrew/Library/Taps/dart-lang/homebrew-dart
        - ~/Library/Caches/Homebrew