description: Restores and saves the gradle cache.
steps:
  - restore_cache:
      keys:
        - v1-gradle-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}-{{ checksum "android/settings.gradle" }}
        - v1-gradle-
  - run:
      name: 'Download Gradle Dependencies'
      command: ./gradlew androidDependencies
      working_directory: android
  - save_cache:
      paths:
        - ~/.gradle
      key: v1-gradle-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}-{{ checksum "android/settings.gradle" }}
