steps:
  - run:
      name: Generate Translations
      command: fvm dart run slang
  - run:
      name: Apply Production Environment
      command: cp .env.production .env
  - run:
      name: Generate Swagger API
      command: fvm dart run build_runner build
  - run:
      name: Restore google-services.json
      command: |
        echo $GOOGLE_SERVICES_JSON | base64 -d > android/app/google-services.json
  - run:
      name: Restore GoogleService-Info.plist
      command: |
        echo $GOOGLE_SERVICE_INFO_PLIST | base64 -d > ios/Runner/GoogleService-Info.plist
