steps:
  - run:
      name: Generate Translations
      command: fvm dart run slang
  - run:
      name: Apply Production Environment
      command: cp .env.prod .env
  - run:
      name: Generate Swagger API
      command: fvm dart run build_runner build
  - run:
      name: Restore google-services.json
      command: |
        echo $GOOGLE_SERVICES_JSON | base64 -d > android/app/google-services.json
