description: Restores and saves the gradle cache.
steps:
  - restore_cache:
      keys:
        - v1-gradle-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}-{{ checksum "android/settings.gradle" }}
        - v1-gradle-
  - run:
      name: '[FL] Download Dependencies'
      command: bundle exec fastlane dependencies
  - save_cache:
      paths:
        - ~/.gradle
      key: v1-gradle-{{ checksum "android/build.gradle" }}-{{ checksum "android/app/build.gradle" }}-{{ checksum "android/settings.gradle" }}
