when:
  and:
    - equal: [main, << pipeline.git.branch >>]
    - not: << pipeline.parameters.api_triggered >>
jobs:
  - bump_version
  - build_android:
      context:
        - app_signing_android
      requires:
        - bump_version
