unless:
  or:
    - equal: [main, << pipeline.git.branch >>]
    - << pipeline.parameters.api_triggered >>
jobs:
  - check
  - bump_version
  - build_android:
      requires:
        - check
        - bump_version
  - build_ios:
      context:
        - app_signing_ios
      requires:
        - check
        - bump_version
