unless:
  or:
    - equal: [main, << pipeline.git.branch >>]
    - << pipeline.parameters.api_triggered >>
jobs:
  - check
  - bump_version:
      prepare_delivery: true
      context:
        - github
  - build_android:
      requires:
        - bump_version
        - check
  - deliver_android:
      production_delivery: false
      requires:
        - build_android
      context:
        - github
