when:
  and:
    - << pipeline.parameters.api_triggered >>
    - equal: [<< pipeline.parameters.workflow_type >>, promotion]
jobs:
  - promote_android:
      context:
        - gruene_google_playstore

  - promote_ios:
      context:
        - gruene_apple_appstore

  - notify_promotion:
      context:
        - github
      requires:
        - promote_android
        - promote_ios
