docker:
  - image: cimg/android:2024.01.1-node
environment:
  GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m" -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2'
resource_class: large
steps:
  - checkout:
      path: ~/project
  - prepare_workspace
  - install_dart_linux
  - install_fvm
  - restore_environment_variables
  - restore_ruby_cache:
      directory: android
  - run:
      name: Install Flutter Packages
      command: |
        fvm flutter pub get --enforce-lockfile
        fvm flutter precache --android
      working_directory: android
#  - run:
#      name: '[FL] Prepare Android Keystore'
#      command: bundle exec fastlane keystore
#      working_directory: android
  - run:
      name: '[FL] Build'
      command: bundle exec fastlane android build version_name:${NEW_VERSION_NAME} version_code:${NEW_VERSION_CODE}
      working_directory: android
  - run:
      name: Make attached_workspace dir
      command: mkdir -p attached_workspace
  - run:
      name: Move aab
      command: mv ~/project/build/app/outputs/bundle/release/app-release.aab ~/attached_workspace/app-release.aab
  - run:
      name: Move apk
      command: mv ~/project/build/app/outputs/apk/release/app-release.apk ~/attached_workspace/app-release.apk
  - persist_to_workspace:
      root: ~/attached_workspace
      paths:
        - app-release.aab
        - app-release.apk
  - store_artifacts:
      path: ~/attached_workspace/
