macos:
  xcode: 16.1.0
environment:
  FASTLANE_SKIP_UPDATE_CHECK: true
steps:
  - checkout
  - prepare_workspace
  - run:
      name: Install rosetta
      command: softwareupdate --install-rosetta --agree-to-license
  - restore_environment_variables
  - install_flutter:
      precache: ios
  - prepare_project
  - install_fastlane:
      directory: ios
  - install_cocoapods
  - run:
      name: '[FL] Build'
      command: bundle exec fastlane ios build version_name:${NEW_VERSION_NAME} version_code:${NEW_VERSION_CODE}
      working_directory: ios
  - store_artifacts:
      path: ~/app-release.ipa
      destination: app-release.ipa
  - persist_to_workspace:
      root: ~/
      paths:
        - app-release.ipa
