macos:
  xcode: 16.1.0
shell: /bin/bash -eo pipefail
environment:
  FASTLANE_SKIP_UPDATE_CHECK: true
steps:
  - checkout
  - prepare_workspace
  - restore_environment_variables
  # Necessary for circle ci mac m1 images
  - run:
      name: Install rosetta
      command: softwareupdate --install-rosetta --agree-to-license
  - install_flutter:
      precache: ios
  - prepare_project
  - install_cocoapods
  - install_fastlane:
      directory: ios
  - run:
      name: '[FL] Build'
      command: bundle exec fastlane ios build version_name:${NEW_VERSION_NAME} version_code:${NEW_VERSION_CODE}
      working_directory: ios
  - store_artifacts:
      path: app-release.ipa
  - persist_to_workspace:
      root: .
      paths:
        - app-release>.ipa