parameters:
  environment:
    type: enum
    default: production
    enum: [production, staging]
docker:
  - image: cimg/android:2024.01.1-node
resource_class: large
shell: /bin/bash -eo pipefail
environment:
  GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m" -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2'
  FASTLANE_SKIP_UPDATE_CHECK: true
steps:
  - checkout
  - prepare_workspace
  - restore_environment_variables
  - install_flutter:
      precache: android
  - prepare_project:
      environment: << parameters.environment >>
  - install_fastlane:
      directory: android
  - install_gradle_dependencies
  - run:
      # The following command is necessary since Ninja is required to build the app for android but is not included in cimg/android
      # https://github.com/CircleCI-Public/cimg-android/issues/129
      name: Install Ninja
      command: sudo apt-get update && sudo apt-get install -y ninja-build
  - run:
      name: '[FL] Prepare Android Keystore'
      command: bundle exec fastlane android keystore
      working_directory: android
  - run:
      name: '[FL] Build'
      command: bundle exec fastlane android build version_name:${NEW_VERSION_NAME} version_code:${NEW_VERSION_CODE} flavor:<< parameters.environment >>
      working_directory: android
  - run:
      name: Move aab
      command: mv ~/project/build/app/outputs/bundle/<< parameters.environment >>Release/app-<< parameters.environment >>-release.aab app-<< parameters.environment >>-release.aab
  - store_artifacts:
      path: app-<< parameters.environment >>-release.aab
  - run:
      name: Move apk
      command: mv ~/project/build/app/outputs/apk/<< parameters.environment >>/release/app-<< parameters.environment >>-release.apk app-<< parameters.environment >>-release.apk
  - store_artifacts:
      path: app-<< parameters.environment >>-release.apk
  - persist_to_workspace:
      root: .
      paths:
        - app-<< parameters.environment >>-release.aab
        - app-<< parameters.environment >>-release.apk
  - persist_environment_variables
