parameters:
  production_delivery:
    description: Whether to deliver the build to production.
    type: boolean
docker:
  - image: cimg/android:2024.08.1-node
resource_class: small
shell: /bin/bash -eo pipefail
environment:
  FASTLANE_SKIP_UPDATE_CHECK: true
steps:
  - checkout
  - prepare_workspace
  - restore_environment_variables
  - install_fastlane:
      directory: android
  - run:
      name: '[FL] Google PlayStore Upload'
      command: bundle exec fastlane android upload aab_path:attached_workspace/app-release.aab production_delivery:"<< parameters.production_delivery >>" version_name:${NEW_VERSION_NAME} version_code:${NEW_VERSION_CODE}
      working_directory: android
