docker:
  - image: cimg/android:2024.08.1-node
resource_class: small
shell: /bin/bash -eo pipefail
environment:
  FASTLANE_SKIP_UPDATE_CHECK: true
steps:
  - checkout
  - install_fastlane:
      directory: android
  - run:
      name: '[FL] Google PlayStore Promotion'
      command: bundle exec fastlane android promote
      working_directory: android
