name: Android Build & Deploymemt

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v3
      - name: Set Staging Vars
        run: |
          echo "APPSTORE_GROUP=DEV" >> $GITHUB_ENV 
          echo "FLUTTER_FLAVOR=staging" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/production-') != true
      - name: Set Prod Vars
        run: |
          echo "APPSTORE_GROUP=PROD" >> $GITHUB_ENV
          echo "FLUTTER_FLAVOR=production" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/production-')
      - name: Flutter action
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: "3.19.0"
          channel: "stable"
          cache: true
      - name: Building Android application
        run: flutter build apk --target lib/main_${{env.FLUTTER_FLAVOR}}.dart --flavor ${{env.FLUTTER_FLAVOR}} --release
